name: gameboo
description: "Gameboo - A gamified mobile application with multiple mini-games, glassmorphism theme, and character system."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  firebase_storage: ^12.4.9

  # Game Engine
  flame: ^1.15.0
  flame_audio: ^2.11.7
  flame_forge2d: ^0.19.0+3

  # Physics & Animation
  flutter_animate: ^4.5.0
  rive: ^0.12.4

  # Audio & Haptics
  audioplayers: ^6.5.0
  vibration: ^3.1.3

  # UI & Animation
  animated_text_kit: ^4.2.2
  lottie: ^3.3.1
  flutter_staggered_animations: ^1.1.1
  confetti: ^0.8.0
  shimmer: ^3.0.0

  # Utilities
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  path_provider: ^2.1.2
  sqflite: ^2.3.0
  uuid: ^4.2.2

  # UI Components
  flutter_svg: ^2.0.9
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#e0e7ef"
  adaptive_icon_foreground: "assets/logo.png"

flutter_native_splash:
  color: "#e0e7ef"
  image: assets/logo.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/
    - assets/images/badge/
    - assets/images/characters/
    - assets/images/games/
    - assets/images/shop/
    - assets/images/shop/tickets/
    - assets/images/shop/monsters/
    - assets/images/shop/characters/
    - assets/images/shop/powerups/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
