// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU_AjW7aAueJ05eQ2xENHaSV-i-4We8kk',
    appId: '1:77702366173:web:5a27880689b0eb87f8ec34',
    messagingSenderId: '77702366173',
    projectId: 'hr360-f8636',
    authDomain: 'hr360-f8636.firebaseapp.com',
    storageBucket: 'hr360-f8636.firebasestorage.app',
    measurementId: 'G-TR0998JDMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0A62PWVxVJIn8fMhEB1Q-XF0-tBlLi5w',
    appId: '1:77702366173:android:75cef39beb330cd0f8ec34',
    messagingSenderId: '77702366173',
    projectId: 'hr360-f8636',
    storageBucket: 'hr360-f8636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpK_fBFCLJpAIrwQZGm4y4MN2IOO1nvQ',
    appId: '1:77702366173:ios:1723eae195ea8916f8ec34',
    messagingSenderId: '77702366173',
    projectId: 'hr360-f8636',
    storageBucket: 'hr360-f8636.firebasestorage.app',
    iosClientId: '77702366173-9r61og1jhlk8rhdchj5tstq17iafgmd3.apps.googleusercontent.com',
    iosBundleId: 'com.abdoanany.gameboo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForMacOS',
    appId: '1:123456789:macos:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'gamex-demo',
    storageBucket: 'gamex-demo.appspot.com',
    iosBundleId: 'com.abdoanany.gameboo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForWindows',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'gamex-demo',
    storageBucket: 'gamex-demo.appspot.com',
  );
}